rm(list = ls())

library(glmnet)
library(FactoMineR)
library(caret)


foldid_vec = function(TT, k) {
  
  seq.interval = split(1:TT, ceiling(seq_along(1:TT)/(TT/k)))
  
  id = rep(0, TT)
  for (j in 1:k) {
    id[seq.interval[[j]]] = j
  }
  
  return(id)
}


Rolling_forecast <- function(Y, X, OutofSampleBegin, Width, TCODE, h = 1, 
                             method.set = c("RW","RW0","RWWD","AR","Plasso.min","Plasso.bic","Slasso.min","Slasso.bic"), 
                             seed = 2023,
                             k = 10, NolagY = F,
                             intercept.Las = TRUE,
                             penalize.lag = T,
                             lag4 = F,
                             factor = F){
  
  if (penalize.lag){
    pf = rep(1,ncol(X))
  }else{
    pf = c(rep(1,ncol(X)-1),0)
  }
  
  set.seed(seed) 
  X = as.matrix(X)
  # Y = as.matrix(Y)
  n = nrow(X)
  p = ncol(X) 
  OoS <-  OutofSampleBegin:n 
  Y.OoS <- Y[OoS]
  
  AE <- matrix(NA,length(method.set),length(OoS))
  SE <- matrix(NA,length(method.set),length(OoS))
  PV <- matrix(NA,length(method.set),length(OoS))
  
  lagY.coef <- matrix(NA,length(method.set),length(OoS))
  
  
  df.act <- matrix(NA,length(method.set),length(OoS))
  df1.act <- matrix(NA,length(method.set),length(OoS))
  df2.act <- matrix(NA,length(method.set),length(OoS))
  df4.act <- matrix(NA,length(method.set),length(OoS))
  df5.act <- matrix(NA,length(method.set),length(OoS))
  df6.act <- matrix(NA,length(method.set),length(OoS))
  df7.act <- matrix(NA,length(method.set),length(OoS))
  
  if (lag4){
    df10.act <- matrix(NA,length(method.set),length(OoS))
    df11.act <- matrix(NA,length(method.set),length(OoS))
    df12.act <- matrix(NA,length(method.set),length(OoS))
    df14.act <- matrix(NA,length(method.set),length(OoS))
    df15.act <- matrix(NA,length(method.set),length(OoS))
    df16.act <- matrix(NA,length(method.set),length(OoS))
    df17.act <- matrix(NA,length(method.set),length(OoS))
    
    df20.act <- matrix(NA,length(method.set),length(OoS))
    df21.act <- matrix(NA,length(method.set),length(OoS))
    df22.act <- matrix(NA,length(method.set),length(OoS))
    df24.act <- matrix(NA,length(method.set),length(OoS))
    df25.act <- matrix(NA,length(method.set),length(OoS))
    df26.act <- matrix(NA,length(method.set),length(OoS))
    df27.act <- matrix(NA,length(method.set),length(OoS))
    
    df30.act <- matrix(NA,length(method.set),length(OoS))
    df31.act <- matrix(NA,length(method.set),length(OoS))
    df32.act <- matrix(NA,length(method.set),length(OoS))
    df34.act <- matrix(NA,length(method.set),length(OoS))
    df35.act <- matrix(NA,length(method.set),length(OoS))
    df36.act <- matrix(NA,length(method.set),length(OoS))
    df37.act <- matrix(NA,length(method.set),length(OoS))
  }
  
  Select.Ind.mat <- matrix(0, length(method.set), dim(X)[2])
  
  for (tt in OoS){
    # print(c(tt,max(OoS)))
    if (tt > Width){
      begin = tt-Width
    }else{
      begin = 1
    }
    Train = begin:(tt-h-1)
    
    X.Train = X[begin:(tt-2*h),]
    Y.Train = Y[(begin+h):(tt-h)]
    n.Train <- length(Y.Train)
    
    X.Test = X[tt-h,]
    
    ### Factors generated by historical data only.
    if (factor == 1){
      # if (!NolagY){
      #   com1 <- prcomp(X.temp[,2:(ncol(X.temp)-1)], center = TRUE,scale. = TRUE)
      # }else{
      #     com1 <- prcomp(X.temp[,2:ncol(X.temp)], center = TRUE,scale. = TRUE)
      #   }
      # # 
     
      if (!lag4){
        com1 <- prcomp( X[1:(tt-h),1:(ncol(X.Train)-4)], center = TRUE,scale. = TRUE)
        X.Train[,(ncol(X.Train)-4) + 1:4] <- com1$x[ begin:(tt-2*h),1:4]
        X.Test[(ncol(X.Train)-4) + 1:4] <- com1$x[ (tt-h),1:4]
      }else{
        for (ddd in 1:4){
          pp0 <- ncol(X.Train)
          # print(c("pp0",pp0))
          com1 <- prcomp( X[1:(tt-h), (ddd-1)*pp0/4 + 1:((pp0)/4 - 4)], center = TRUE,scale. = TRUE)
          X.Train[,(ddd-1)*pp0/4 + (pp0/4-4) + 1:4] <- com1$x[begin:(tt-2*h) ,1:4]
          
          X.Test[(ddd-1)*pp0/4 + (pp0/4-4) + 1:4] <- com1$x[ (tt-h),1:4]
        }
        
        
      }
      
     
  
    }
    
    
   
    for (im in 1:length(method.set)){
      
      df = NA
      df1 = NA
      df2 = NA
      df4 = NA
      df5 = NA
      df6 = NA
      df7 = NA
      
      df10 = NA
      df11 = NA
      df12 = NA
      df14 = NA
      df15 = NA
      df16 = NA
      df17 = NA
      
      df20 = NA
      df21 = NA
      df22 = NA
      df24 = NA
      df25 = NA
      df26 = NA
      df27 = NA
      
      df30 = NA
      df31 = NA
      df32 = NA
      df34 = NA
      df35 = NA
      df36 = NA
      df37 = NA
      method = method.set[im]
      if (method == "RWWD"){
        y.hat <- Y[tt-h] + h / n * (Y.Train[n.Train] - Y.Train[1])
      }else if (method == "AR"){
        BICs = rep(NA,13)
        for (qq in 0:12){
          X.AR <- NULL
          for (iq in 0:qq){
            Y.lag <- Y[(begin+qq-iq):(tt-2*h-iq)]
            X.AR <- cbind(X.AR,Y.lag)
          }
          out.OLS <- lm(Y.Train[(n.Train-nrow(X.AR)+1):n.Train]~X.AR)
          residual <- out.OLS$residuals
          n.use <- length(residual)
          BICs[qq+1] <- log( sum(residual^2) /  n.use ) + (qq+1) * log(n.use) / n.use 
        }
        qq.select <- which.min(BICs) - 1 
        X.AR <- NULL 
        for (iq in 0:qq.select){
          Y.lag <- Y[(begin+qq.select-iq):(tt-2*h-iq)]
          X.AR <- cbind(X.AR,Y.lag)
        }
        out.AR <- lm(Y.Train[(n.Train-nrow(X.AR)+1):n.Train] ~ X.AR)
        # Y.Train.Las <- Y.Train[(n.Train-nrow(X.AR)+1):n.Train]
        # X.Train.Las <- cbind(X.AR,X.Train[(n.Train-nrow(X.AR)+1):n.Train,])
        coef.AR <- out.AR$coefficients 
        X.AR = NULL
        for (iq in 0:qq.select){
          # if (begin>iq){
          #   begin.AR <- begin-iq
          # }else{begin.AR <- 1}
          Y.lag <- Y[tt-h-iq]
          X.AR <- cbind(X.AR,Y.lag)
        }
        
        y.hat <- cbind(1,X.AR) %*% coef.AR
      }else if (method == "Plasso.min"){
          
          Y.Train.Las = Y.Train
          X.Train.Las = X.Train
          # print(sum( !is.numeric(X.Train.Las)))
         
          out.Las <- cv.glmnet(X.Train.Las,Y.Train.Las,foldid = foldid_vec(nrow(X.Train.Las),k), intercept = intercept.Las, 
                               standardize = F ,penalty.factor = pf, )
         coef.Las <- as.vector(coef(out.Las, s = out.Las$lambda.min))
         
       
        y.hat <-  sum(c(1,X.Test) * coef.Las )
        lagY.coef[im,tt-OutofSampleBegin+1] <-  coef.Las[length(coef.Las)] 
        len.theta = length(coef.Las)
        
        Select.Ind <- coef.Las[-1] != 0
        
        
        if (lag4){
          df = sum( coef.Las[-1] != 0 & ( TCODE >= 1 & TCODE <= 7) ) 
          df1 = sum( coef.Las[-1] != 0 & TCODE == 1)
          df2 = sum( coef.Las[-1] != 0 & TCODE == 2) 
          df4 = sum( coef.Las[-1] != 0 & TCODE == 4)
          df5 = sum( coef.Las[-1] != 0 & TCODE == 5)
          df6 = sum( coef.Las[-1] != 0 & TCODE == 6)
          df7 = sum( coef.Las[-1] != 0 & TCODE == 7)
          
          df10 = sum( coef.Las[-1] != 0 & ( TCODE >= 11 & TCODE <= 17)) 
          df11 = sum( coef.Las[-1] != 0 & TCODE == 11)
          df12 = sum( coef.Las[-1] != 0 & TCODE == 12) 
          df14 = sum( coef.Las[-1] != 0 & TCODE == 14)
          df15 = sum( coef.Las[-1] != 0 & TCODE == 15)
          df16 = sum( coef.Las[-1] != 0 & TCODE == 16)
          df17 = sum( coef.Las[-1] != 0 & TCODE == 17)
          
          
          df20 = sum( coef.Las[-1] != 0 & ( TCODE >= 21 & TCODE <= 27) )
          df21 = sum( coef.Las[-1] != 0 & TCODE == 21)
          df22 = sum( coef.Las[-1] != 0 & TCODE == 22) 
          df24 = sum( coef.Las[-1] != 0 & TCODE == 24)
          df25 = sum( coef.Las[-1] != 0 & TCODE == 25)
          df26 = sum( coef.Las[-1] != 0 & TCODE == 26)
          df27 = sum( coef.Las[-1] != 0 & TCODE == 27)
          
          df30 = sum( coef.Las[-1] != 0 & ( TCODE >= 31 & TCODE <= 37))
          df31 = sum( coef.Las[-1] != 0 & TCODE == 31)
          df32 = sum( coef.Las[-1] != 0 & TCODE == 32) 
          df34 = sum( coef.Las[-1] != 0 & TCODE == 34)
          df35 = sum( coef.Las[-1] != 0 & TCODE == 35)
          df36 = sum( coef.Las[-1] != 0 & TCODE == 36)
          df37 = sum( coef.Las[-1] != 0 & TCODE == 37)
          
        }else{
          df = sum( coef.Las[-1] != 0)
          df1 = sum( coef.Las[-1] != 0 & TCODE == 1)
          df2 = sum( coef.Las[-1] != 0 & TCODE == 2) 
          df4 = sum( coef.Las[-1] != 0 & TCODE == 4)
          df5 = sum( coef.Las[-1] != 0 & TCODE == 5)
          df6 = sum( coef.Las[-1] != 0 & TCODE == 6)
          df7 = sum( coef.Las[-1] != 0 & TCODE == 7)
        }
        
        
      }else  if (method == "Slasso.min"){
         
         Y.Train.Las = Y.Train
         X.Train.Las = X.Train
          
        out.Las <- cv.glmnet(X.Train.Las,Y.Train.Las,foldid = foldid_vec(nrow(X.Train.Las),k),
                             standardize = T, intercept  = intercept.Las,penalty.factor = pf)
        coef.Las <- as.vector(coef(out.Las, s = out.Las$lambda.min))
        
        
      y.hat <- sum(c(1,X.Test) * coef.Las )
      
      lagY.coef[im,tt-OutofSampleBegin+1] <-  coef.Las[length(coef.Las)] 
      # print(c( lagY.coef[im-1,tt-OutofSampleBegin+1], coef.Las[length(coef.Las)] ))
      Select.Ind <- coef.Las[-1] != 0
      # print(X.Train[,TCODE==8])
      if (lag4){
        df = sum( coef.Las[-1] != 0 & ( TCODE >= 1 & TCODE <= 7) ) 
        df1 = sum( coef.Las[-1] != 0 & TCODE == 1)
        df2 = sum( coef.Las[-1] != 0 & TCODE == 2) 
        df4 = sum( coef.Las[-1] != 0 & TCODE == 4)
        df5 = sum( coef.Las[-1] != 0 & TCODE == 5)
        df6 = sum( coef.Las[-1] != 0 & TCODE == 6)
        df7 = sum( coef.Las[-1] != 0 & TCODE == 7)
        
        df10 = sum( coef.Las[-1] != 0 & ( TCODE >= 11 & TCODE <= 17)) 
        df11 = sum( coef.Las[-1] != 0 & TCODE == 11)
        df12 = sum( coef.Las[-1] != 0 & TCODE == 12) 
        df14 = sum( coef.Las[-1] != 0 & TCODE == 14)
        df15 = sum( coef.Las[-1] != 0 & TCODE == 15)
        df16 = sum( coef.Las[-1] != 0 & TCODE == 16)
        df17 = sum( coef.Las[-1] != 0 & TCODE == 17)
        
        
        df20 = sum( coef.Las[-1] != 0 & ( TCODE >= 21 & TCODE <= 27) )
        df21 = sum( coef.Las[-1] != 0 & TCODE == 21)
        df22 = sum( coef.Las[-1] != 0 & TCODE == 22) 
        df24 = sum( coef.Las[-1] != 0 & TCODE == 24)
        df25 = sum( coef.Las[-1] != 0 & TCODE == 25)
        df26 = sum( coef.Las[-1] != 0 & TCODE == 26)
        df27 = sum( coef.Las[-1] != 0 & TCODE == 27)
        
        df30 = sum( coef.Las[-1] != 0 & ( TCODE >= 31 & TCODE <= 37))
        df31 = sum( coef.Las[-1] != 0 & TCODE == 31)
        df32 = sum( coef.Las[-1] != 0 & TCODE == 32) 
        df34 = sum( coef.Las[-1] != 0 & TCODE == 34)
        df35 = sum( coef.Las[-1] != 0 & TCODE == 35)
        df36 = sum( coef.Las[-1] != 0 & TCODE == 36)
        df37 = sum( coef.Las[-1] != 0 & TCODE == 37)
        
      }else{
        df = sum( coef.Las[-1] != 0)
        df1 = sum( coef.Las[-1] != 0 & TCODE == 1)
        df2 = sum( coef.Las[-1] != 0 & TCODE == 2) 
        df4 = sum( coef.Las[-1] != 0 & TCODE == 4)
        df5 = sum( coef.Las[-1] != 0 & TCODE == 5)
        df6 = sum( coef.Las[-1] != 0 & TCODE == 6)
        df7 = sum( coef.Las[-1] != 0 & TCODE == 7)
      }
      
      }
      AE[im,tt-OutofSampleBegin+1] <-  abs(y.hat - Y[tt])
      SE[im,tt-OutofSampleBegin+1] <-  (y.hat - Y[tt])^2
      PV[im,tt-OutofSampleBegin+1] <-  y.hat
      
      
      if (   grepl("lasso", method)    ){
        Select.Ind.mat[im,] <-  Select.Ind.mat[im,] +  Select.Ind
      }
      
      df.act[im,tt-OutofSampleBegin+1] <-  df
      df1.act[im,tt-OutofSampleBegin+1] <-  df1
      df2.act[im,tt-OutofSampleBegin+1] <-  df2
      df4.act[im,tt-OutofSampleBegin+1] <-  df4
      df5.act[im,tt-OutofSampleBegin+1] <-  df5
      df6.act[im,tt-OutofSampleBegin+1] <-  df6
      df7.act[im,tt-OutofSampleBegin+1] <-  df7
      
      if (lag4){
        df10.act[im,tt-OutofSampleBegin+1] <-  df10
        df11.act[im,tt-OutofSampleBegin+1] <-  df11
        df12.act[im,tt-OutofSampleBegin+1] <-  df12
        df14.act[im,tt-OutofSampleBegin+1] <-  df14
        df15.act[im,tt-OutofSampleBegin+1] <-  df15
        df16.act[im,tt-OutofSampleBegin+1] <-  df16
        df17.act[im,tt-OutofSampleBegin+1] <-  df17
        
        df20.act[im,tt-OutofSampleBegin+1] <-  df20
        df21.act[im,tt-OutofSampleBegin+1] <-  df21
        df22.act[im,tt-OutofSampleBegin+1] <-  df22
        df24.act[im,tt-OutofSampleBegin+1] <-  df24
        df25.act[im,tt-OutofSampleBegin+1] <-  df25
        df26.act[im,tt-OutofSampleBegin+1] <-  df26
        df27.act[im,tt-OutofSampleBegin+1] <-  df27
        
        df30.act[im,tt-OutofSampleBegin+1] <-  df30
        df31.act[im,tt-OutofSampleBegin+1] <-  df31
        df32.act[im,tt-OutofSampleBegin+1] <-  df32
        df34.act[im,tt-OutofSampleBegin+1] <-  df34
        df35.act[im,tt-OutofSampleBegin+1] <-  df35
        df36.act[im,tt-OutofSampleBegin+1] <-  df36
        df37.act[im,tt-OutofSampleBegin+1] <-  df37
      }
       
    }
    
    
  } 
  
  
  
  if (lag4){
    return.list <- list(SE = SE, AE = AE, PV = PV,
                        Select.variable = Select.Ind.mat,
                        df = df.act,
                        df1 = df1.act,
                        df2 = df2.act,
                        df4 = df4.act,
                        df5 = df5.act,
                        df6 = df6.act,
                        df7 = df7.act,
                        
                        df10 = df10.act,
                        df11 = df11.act,
                        df12 = df12.act,
                        df14 = df14.act,
                        df15 = df15.act,
                        df16 = df16.act,
                        df17 = df17.act,
                        
                        df20 = df20.act,
                        df21 = df21.act,
                        df22 = df22.act,
                        df24 = df24.act,
                        df25 = df25.act,
                        df26 = df26.act,
                        df27 = df27.act,
                        
                        df30 = df30.act,
                        df31 = df31.act,
                        df32 = df32.act,
                        df34 = df34.act,
                        df35 = df35.act,
                        df36 = df36.act,
                        df37 = df37.act
    )
  }else{
    return.list <- list(SE = SE, AE = AE, PV = PV, 
                        Select.variable = Select.Ind.mat,
                        df = df.act,
                        df1 = df1.act,
                        df2 = df2.act,
                        df4 = df4.act,
                        df5 = df5.act,
                        df6 = df6.act,
                        df7 = df7.act
    )
  }
  
  
  return(return.list)
  
}

empirical.predict <- function(name.outcome, transform, accumulative = F, Width = NULL, lag4 = 1, factor = 1, h.max = 3, 
                              start.time = "1/1/1990", growthrate = FALSE, 
                              NolagY = F,
                              method.set = c("RWWD","AR","Plasso.min","Slasso.min")){
  
 
  df <- read.csv("current.csv")
  trans <- read.csv("trans.csv")$Transform 
 
 
  nn <- nrow(df)
  df_use <- df[2:nn,]
  df_lag <- df[1:(nn-1),]
  
  if (growthrate == T){
    index = df_use[,name.outcome]
    index_lag <- df_lag[,name.outcome]
    Y = (log(index) - log(index_lag)) * 100
    Y = index - index_lag
  }else{
    Y = df_use[,name.outcome]
  }
  
  
  if (transform == 1){
    df_use <- df[3:nrow(df),]
    df_lag <- df[2:(nrow(df)-1),]
    df_lag_2 <- df[1:(nrow(df)-2),]
    index = df_use[,name.outcome]
    index_lag <- df_lag[,name.outcome]
    if (growthrate == T){
      Y = (log(index) - log(index_lag)) * 100
      Y = index - index_lag
    }else{
      Y = index
    }
    
    
    for (pp in 2:ncol(df)){
      if (trans[pp-1] == 2){
        df_use[,pp] = df_use[,pp] - df_lag[,pp] 
      }else if(trans[pp-1] == 3){
        df_use[,pp] = df_use[,pp] - 2*df_lag[,pp] + df_lag_2[,pp]
      }else if(trans[pp-1] == 4){
        df_use[,pp] = log(df_use[,pp]) 
      }else if(trans[pp-1] == 5){
        df_use[,pp] = log(df_use[,pp]) -  log(df_lag[,pp])
      }else if(trans[pp-1] == 6){
        df_use[,pp] = log(df_use[,pp]) -  2*log(df_lag[,pp]) + log(df_lag_2[,pp])
      }else if(trans[pp-1] == 7){
        df_use[,pp] = df_use[,pp]/df_lag[,pp] - df_lag[,pp]/df_lag_2[,pp]
      }
    }
    
  } 
 
  
  X.temp = df_use[,-which(names(df_use) %in% name.outcome)]
  
  if (!NolagY){
    X.temp[,name.outcome] <- Y
  }
   
  
   delete = NULL
  
  for (pp in 2:ncol(X.temp)){
    # if (sum(is.na(X.temp[,pp]))>0 | names(X.temp)[pp] %in% multi_colinear ){
    if (sum(is.na(X.temp[,pp]))>0 ){
      delete = c(delete,pp)
    }
  } 
 
  
  X.temp = X.temp[,-delete]
  
  if (!NolagY){
    trans = c(trans[ - (which(names(df_use) %in% name.outcome) -  1)],8)
    name.keep <- c(names(df_use)[ - (which(names(df_use) %in% name.outcome))],"UNRATE")
  }else{
    trans = trans[ - (which(names(df_use) %in% name.outcome) -  1)]
    name.keep <- names(df_use)[ - (which(names(df_use) %in% name.outcome))]
  }
  

 
  # print(table(trans[-(delete-1)]))
   
  trans.keep <- trans[-(delete-1)]
  name.keep <- name.keep[-delete]
  name.keep <- name.keep[-1]
 
  if (factor == 1){
    
   
    com1 <- prcomp(X.temp[,2:ncol(X.temp)], center = TRUE,scale. = TRUE)
    Factor <- com1$x[,1:4]
    
    
  
    X.temp[,"F1"] <- Factor[,1]
    X.temp[,"F2"] <- Factor[,2]
    X.temp[,"F3"] <- Factor[,3]
    X.temp[,"F4"] <- Factor[,4]
    # print(colnames(X.temp))
    
    trans.keep <- c(trans.keep,rep(0,4))
    name.keep <- c(name.keep,"F1","F2","F3","F4")
  }
  
  
  # lag4 = 1
  if (lag4 == 1){
    X_current <- X.temp[4:nrow(X.temp),]
    X_lag <- X.temp[3:(nrow(X.temp)-1),2:ncol(X.temp)]
    X_lag_2 <- X.temp[2:(nrow(X.temp)-2),2:ncol(X.temp)]
    X_lag_3 <- X.temp[1:(nrow(X.temp)-3),2:ncol(X.temp)]
    # X_lag_4 <- X.temp[1:(nrow(X.temp)-4),2:ncol(X.temp)]
    X = cbind(X_current,X_lag,X_lag_2,X_lag_3)
    Y = X_current[,name.outcome]
    trans.keep <- c(trans.keep,trans.keep+10,trans.keep+20,trans.keep+30)
    name.keep <-  c(name.keep,paste0("L1.",name.keep),paste0("L2.",name.keep),paste0("L3.",name.keep))
  }else{
    
    X = X.temp
    if (!NolagY){
      Y = X[,name.outcome]
    }
  }
  
  # print(c("name.keep",length(name.keep)))
  # X = X[,-which(names(X) %in% name.outcome )]
    
  # CPI = df_use$CPIAUCSL
  OutofSampleBegin <- which(X$sasdate %in% start.time)
  
  if (is.null(Width)){
    Width <- OutofSampleBegin - 1
  }
  
  # accumulate <- 0 
  
  if (!accumulative){
    h.seq = 1:h.max
  }else{
    h.seq = 1:h.max
  }
  
   
 
  # print(method.set)
  
  RMSE <- matrix(NA,length(h.seq),length(method.set))
  MAE <- matrix(NA,length(h.seq),length(method.set)) 
  
  X = X[,!(names(X) == "sasdate")]
  
  if (transform == 0){
    trans.text = "NT"
  }else{
    trans.text = "ST"
  }
  
  
  print(paste0("Transformation: ",trans.text))
  print(paste0("Rolling window: ",Width, " periods"))
  print(paste0("Number of regressors: ",dim(X)[2]))
  
  out <- list()
  
  
  penalize.lag = TRUE 
  
  # print(c("dim",dim(X)[2]))
  
  for (ih in 1:length(h.seq)){
    
    
    print(paste0("Running h = ",ih," / ",h.max))
    h = h.seq[ih]
    
    if (!accumulative){
      YY = Y 
    }else{
      YY = rep(NA,length(Y))
      for (iii in 1:length(Y)){
        if (iii <= h){
          YY[iii] = sum(Y[1:iii])
        }else{
          YY[iii] = sum(Y[(iii-h+1):iii])
        }
      }
    }
     
    out[[ih]] <- Rolling_forecast(YY, X, OutofSampleBegin, Width = Width, penalize.lag = penalize.lag, NolagY = NolagY,
                            h = h, method.set = method.set, seed = 2023, TCODE = trans.keep, lag4=lag4, factor = factor)
    RMSE[ih,] <- sqrt(rowMeans(out[[ih]]$SE))
    MAE[ih,] <- rowMeans(out[[ih]]$AE) 
    out[[ih]]$TCODE = trans.keep
    out[[ih]]$ID = name.keep
    # # print( df_print ) 
   
   
  }
  RMSE <- cbind(1:h.max,RMSE)
  colnames(RMSE) <- c("h",method.set)
  rownames(RMSE)
  
  print("RMSE")
  print( RMSE )
  
  MAE <- cbind(1:h.max,MAE)
  colnames(MAE) <- c("h",method.set) 
  
  print("MAE")
  print( MAE )
  file = paste0("RDS/",name.outcome,"Trans",transform, "Accum", accumulative, "Width", Width, "NolagY",NolagY, ".RDS")
  saveRDS(out, file = file)
}
